amp/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.staticfiles.urls import urlpatterns
from django.urls import path

from amp import views

urlpatterns += [
    path("", views.Landing.as_view(), name="landing"),
    path("dashboard", views.Dashboard.as_view(), name="dashboard"),
    path("requests/employee/new", views.NewEmployeeRequest.as_view(), name="new-employee-request"),
    path(
        "requests/contractor/new",
        views.NewContractorRequest.as_view(),
        name="new-contractor-request",
    ),
    path(
        "dashboard/account/general/update",
        views.AccountGeneralUpdate.as_view(),
        name="account-general-update",
    ),
    path(
        "dashboard/account/password/change",
        views.AccountPasswordChange.as_view(),
        name="account-password-change",
    ),
    path("dashboard/users", views.ListUsers.as_view(), name="list-users"),
    path("dashboard/users/new", views.NewUser.as_view(), name="new-user"),
    path("dashboard/users/<int:user_pk>/update", views.UpdateUser.as_view(), name="update-user"),
    path("dashboard/users/<int:user_pk>/delete", views.DeleteUser.as_view(), name="delete-user"),
    path("dashboard/logs", views.ListLogs.as_view(), name="list-logs"),
    path("dashboard/logs/csv", views.CSVLogs.as_view(), name="csv-logs"),
    path("dashboard/employees", views.ListEmployees.as_view(), name="list-employees"),
    path("dashboard/employees/csv", views.CSVEmployees.as_view(), name="csv-employees"),
    path("dashboard/employees/new", views.NewEmployee.as_view(), name="new-employee"),
    path(
        "dashboard/employees/<int:employee_pk>/update",
        views.UpdateEmployee.as_view(),
        name="update-employee",
    ),
    path(
        "dashboard/employees/<int:employee_pk>/delete",
        views.DeleteEmployee.as_view(),
        name="delete-employee",
    ),
    path(
        "dashboard/employees/<int:employee_pk>/documents/new",
        views.NewEmployeeDocument.as_view(),
        name="new-employee-document",
    ),
    path(
        "dashboard/employees/<int:employee_pk>/documents/<int:document_pk>/delete",
        views.DeleteEmployeeDocument.as_view(),
        name="delete-employee-document",
    ),
    path("dashboard/contractors", views.ListContractors.as_view(), name="list-contractors"),
    path("dashboard/contractors/csv", views.CSVContractors.as_view(), name="csv-contractors"),
    path("dashboard/contractors/new", views.NewContractor.as_view(), name="new-contractor"),
    path(
        "dashboard/contractors/<int:contractor_pk>/update",
        views.UpdateContractor.as_view(),
        name="update-contractor",
    ),
    path(
        "dashboard/contractors/<int:contractor_pk>/delete",
        views.DeleteContractor.as_view(),
        name="delete-contractor",
    ),
    path(
        "dashboard/contractors/<int:contractor_pk>/documents/new",
        views.NewContractorDocument.as_view(),
        name="new-contractor-document",
    ),
    path(
        "dashboard/contractors/<int:contractor_pk>/documents/<int:document_pk>/delete",
        views.DeleteContractorDocument.as_view(),
        name="delete-contractor-document",
    ),
    path("dashboard/permissions", views.ListPermissions.as_view(), name="list-permissions"),
    path("dashboard/permissions/csv", views.CSVPermissions.as_view(), name="csv-permissions"),
    path("dashboard/permissions/new", views.NewPermission.as_view(), name="new-permission"),
    path(
        "dashboard/permissions/<int:permission_pk>",
        views.DetailPermission.as_view(),
        name="detail-permission",
    ),
    path(
        "dashboard/permissions/<int:permission_pk>/update",
        views.UpdatePermission.as_view(),
        name="update-permission",
    ),
    path(
        "dashboard/permissions/<int:permission_pk>/delete",
        views.DeletePermission.as_view(),
        name="delete-permission",
    ),
    path("dashboard/requests", views.RequestsList.as_view(), name="list-requests"),
    path(
        "dashboard/requests/employees/<int:request_pk>/approve",
        views.ApproveEmployeeRequest.as_view(),
        name="approve-employee-request",
    ),
    path(
        "dashboard/requests/employees/<int:request_pk>/reject",
        views.RejectEmployeeRequest.as_view(),
        name="reject-employee-request",
    ),
    path(
        "dashboard/requests/employees/<int:request_pk>",
        views.DetailEmployeeRequest.as_view(),
        name="detail-employee-request",
    ),
    path(
        "dashboard/requests/contractors/<int:request_pk>/approve",
        views.ApproveContractorRequest.as_view(),
        name="approve-contractor-request",
    ),
    path(
        "dashboard/requests/contractors/<int:request_pk>/reject",
        views.RejectContractorRequest.as_view(),
        name="reject-contractor-request",
    ),
    path(
        "dashboard/requests/contractors/<int:request_pk>",
        views.DetailContractorRequest.as_view(),
        name="detail-contractor-request",
    ),
    path("admin", admin.site.urls),
    path("login", LoginView.as_view(), name="login"),
    path("logout", LogoutView.as_view(), name="logout"),
]

amp/models.py
from django.contrib.auth import get_user_model
from django.db import models

CIP_MANAGER = "CIP Manager"
ALTERNATE_CIP_MANAGER = "Alternate CIP Manager"
ACCESS_CONTROL_ENGINEER = "Access Control Engineer"
TRAINING_COORDINATOR = "Training Coordinator"
HUMAN_RESOURCES = "Human Resources"
PROFILE_TITLES = (
    (CIP_MANAGER, CIP_MANAGER),
    (ALTERNATE_CIP_MANAGER, ALTERNATE_CIP_MANAGER),
    (ACCESS_CONTROL_ENGINEER, ACCESS_CONTROL_ENGINEER),
    (TRAINING_COORDINATOR, TRAINING_COORDINATOR),
    (HUMAN_RESOURCES, HUMAN_RESOURCES),
)

LOG_CATEGORIES = (
    ("Approval", "Approval"),
    ("Rejection", "Rejection"),
    ("New Employee", "New Employee"),
    ("New Contractor", "New Contractor"),
    ("Permission Change", "Permission Change"),
    ("New Employee Permission Request", "New Employee Permission Request"),
    ("New Contractor Permission Request", "New Contractor Permission Request"),
)


class Permission(models.Model):
    name = models.CharField(max_length=160)

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(
        get_user_model(), models.CASCADE, related_name="%(app_label)s_profile"
    )
    title = models.CharField(max_length=80, choices=PROFILE_TITLES, null=True, blank=True)

    def __str__(self):
        return self.user.username

    def is_cip(self):
        return self.title == CIP_MANAGER or self.title == ALTERNATE_CIP_MANAGER

    def is_ace(self):
        return self.title == ACCESS_CONTROL_ENGINEER

    def is_tc(self):
        return self.title == TRAINING_COORDINATOR

    def is_hr(self):
        return self.title == HUMAN_RESOURCES


class Resource(models.Model):
    first_name = models.CharField(max_length=80)
    last_name = models.CharField(max_length=80)

    permissions = models.ManyToManyField(Permission, related_name="%(class)ss")

    background_check = models.FileField(
        upload_to="background", blank=True, null=True, help_text="This field is not required."
    )
    last_background_check_date = models.DateField(
        blank=True, null=True, help_text="This field is not required. Ex. 2012-05-13"
    )
    last_training_date = models.DateField(
        blank=True, null=True, help_text="This is field is not required. Ex. 2012-05-13"
    )

    class Meta:
        abstract = True

    def __str__(self):
        return self.get_full_name()

    def get_full_name(self):
        return "{first_name} {last_name}".format(
            last_name=self.last_name, first_name=self.first_name
        )

    def permission_change_log(self, old_permissions):
        new_permissions = [permission.name for permission in self.permissions.all()]
        old_permissions = [permission.name for permission in old_permissions]

        old_permissions_msg = ", ".join(old_permissions) if old_permissions else "No Permissions"
        new_permissions_msg = ", ".join(new_permissions) if new_permissions else "No Permissions"

        return {
            "category": "Permission Change",
            "accessor": str(self),
            "description": (
                "{resource}'s permissions have been changed "
                "from [{old_permission_msg}] to [{new_permission_msg}]."
            ).format(
                resource=str(self),
                old_permission_msg=old_permissions_msg,
                new_permission_msg=new_permissions_msg,
            ),
        }

    def creation_log(self):
        if self.permissions.exists():
            description = "{resource} added to the system with permissions: {permissions}.".format(
                resource=str(self),
                permissions=", ".join([str(permission) for permission in self.permissions.all()]),
            )
        else:
            description = "{resource} added to the system without permissions.".format(
                resource=str(self)
            )

        category = "New {resource_type}".format(
            resource_type=self.__class__._meta.verbose_name.title()
        )
        return {"category": category, "accessor": str(self), "description": description}


class Employee(Resource):
    def __str__(self):
        return "Employee {resource}".format(resource=super().__str__())


class EmployeeDocument(models.Model):
    file = models.FileField(upload_to="employee-documents")
    employee = models.ForeignKey(
        Employee,
        models.CASCADE,
        help_text="Which employee does this file reference?",
        related_name="documents",
    )

    def __str__(self):
        return "{file} - {employee}".format(file=self.file, employee=str(self.employee))


class Contractor(Resource):
    employer = models.CharField(max_length=80)

    def __str__(self):
        return "Contractor {resource}".format(resource=super().__str__())


class ContractorDocument(models.Model):
    file = models.FileField(upload_to="contractor-documents")
    contractor = models.ForeignKey(
        Contractor,
        models.CASCADE,
        help_text="Which contractor does this file reference?",
        related_name="documents",
    )

    def __str__(self):
        return "{file} - {contractor}".format(file=self.file, contractor=str(self.contractor))


class Log(models.Model):
    ACCESSORS = (("Employee", "Employee"), ("Contractor", "Contractor"))

    category = models.CharField(max_length=160, choices=LOG_CATEGORIES)

    author = models.CharField(max_length=160)

    accessor = models.CharField(max_length=160)

    description = models.TextField()
    creation_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "Log: {msg}".format(
            msg=(self.description[:32] + "...") if len(self.description) > 35 else self.description
        )


class Request(models.Model):
    permissions = models.ManyToManyField(Permission, related_name="%(class)s_requests")

    hr_status = models.NullBooleanField(blank=True, null=True)
    tc_status = models.NullBooleanField(blank=True, null=True)
    ace_status = models.NullBooleanField(blank=True, null=True)
    cip_status = models.NullBooleanField(blank=True, null=True)

    class Meta:
        abstract = True

    def __str__(self):
        return "{permissions_count} permissions to {resource_display}".format(
            permissions_count=self.permissions.count(), resource_display=self.get_resource_display()
        )

    def is_approved(self):
        return self.hr_status and self.tc_status and self.ace_status and self.cip_status

    def is_rejected(self):
        return (
            self.hr_status is False
            and self.tc_status is False
            and self.ace_status is False
            and self.cip_status is False
        )

    def creation_log(self):
        resource_display = self.get_resource_display()
        resource_type = self.get_resource_type()
        return {
            "category": "New {resource_type} Permission Request".format(
                resource_type=resource_type
            ),
            "accessor": resource_display,
            "description": "{resource_display} requesting the following permissions: {permissions}.".format(
                resource_display=resource_display,
                permissions=", ".join(self.permissions.values_list("name", flat=True)),
            ),
        }


class EmployeeRequest(Request):
    employee = models.ForeignKey(Employee, models.CASCADE)

    def get_resource_display(self):
        return self.employee.get_full_name()

    def get_resource_type(self):
        return self.employee.__class__._meta.verbose_name.title()


class ContractorRequest(Request):
    first_name = models.CharField(max_length=80)
    last_name = models.CharField(max_length=80)
    email = models.EmailField()
    employer = models.CharField(max_length=80)

    remote = models.BooleanField(help_text="Will you be accessing remotely?")

    background_check = models.FileField(upload_to="background", blank=True, null=True)

    def get_resource_display(self):
        return "{first_name} {last_name}".format(
            last_name=self.last_name, first_name=self.first_name
        )

    def get_resource_type(self):
        return "Contractor"

app-server/app/forms/company.py
"""
Define the forms that will be used by the Company views.
"""

from api.models import Company
from authentication.models import User

from django import forms


class NewCompanyUserForm(forms.ModelForm):
    """
    This form will be used when a new Company User is being created.
    """
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password Confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'company', 'title')
        widgets = {
            'company': forms.HiddenInput()
        }

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request')
        super(NewCompanyUserForm, self).__init__(*args, **kwargs)
        self.fields['company'].initial = request.user.company.pk
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['title'].required = True
        self.request = request

    def clean_password2(self):
        """
        Check that the two password entries match.
        """
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 != password2:
            raise forms.ValidationError('Password do not match.')
        
        return password2

    def clean_title(self):
        """
        Check that if the title is not Access Control Engineer there is only 1.
        """
        title = self.cleaned_data.get('title')
        if title == 'Access Control Engineer' or title == 'Human Resources':
            return title
        else:
            users = User.objects.filter(company=self.request.user.company, title=title)
            if users:
                raise forms.ValidationError('A user with this title already exists. "Access Control Engineer" and "Human Resoures" are the only positions that can be held by multiple Users.')
            else:
                return title

    def save(self, commit=True):
        """
        Save the provided password in hashed format.
        """
        user = super(NewCompanyUserForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class UpdateCompanyUserForm(forms.ModelForm):
    """
    This form will be used when a Company User is updated.
    """
    new_password = forms.CharField(widget=forms.PasswordInput, required=False)

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'title')

    def __init__(self, *args, **kwargs):
        super(UpdateCompanyUserForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['title'].required = True

    def save(self, commit=True):
        """
        Save the form and if the user has provided a new password, set it.

        Additionally, provide support for a user to have commit set to
        `False` and not save the created object.
        """
        user = super(UpdateCompanyUserForm, self).save(commit=False)
        if self.cleaned_data['new_password']:
            user.set_password(self.cleaned_data['new_password'])
        if commit:
            user.save()

        return user

app/templates/new_contractor.html
{% extends "basenav.html" %}

{% block title %}New Conctractor | AMP{% endblock %}

{% block content %}

<!-- Jumbotron -->
<div class="jumbotron">
    <div class="container">
        <h1>New Contractor!</h1>
        <p>This page allows you to create a new Contractor.</p>
    </div>
</div>

<div class="container">
    <!-- Breadcrumbs -->
    <ol class="breadcrumb">
      <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
      <li><a href="{% url 'contractors' %}">Contractors</a></li>
      <li class="active">New</li>
    </ol>

    <form class="form-horizontal" role="form" method="post">
        {% csrf_token %}

        {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">{{form.non_field_errors}}</div>
        {% endif %}

        <div class="form-group">
            {% if form.email.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.email.errors}}</div>
            {% endif %}
            <label for="id_email" class="col-sm-2 control-label">Email:</label>
            <div class="col-sm-10">
                {{form.email}}
            </div>
        </div>

        <div class="form-group">
            {% if form.first_name.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.first_name.errors}}</div>
            {% endif %}
            <label for="id_first_name" class="col-sm-2 control-label">First Name:</label>
            <div class="col-sm-10">
                {{form.first_name}}
            </div>
        </div>

        <div class="form-group">
            {% if form.last_name.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.last_name.errors}}</div>
            {% endif %}
            <label for="id_last_name" class="col-sm-2 control-label">Last Name:</label>
            <div class="col-sm-10">
                {{form.last_name}}
            </div>
        </div>

        <div class="form-group">
            {% if form.employer.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.employer.errors}}</div>
            {% endif %}
            <label for="id_employer" class="col-sm-2 control-label">Employer:</label>
            <div class="col-sm-10">
                {{form.employer}}
            </div>
        </div>

        <div class="form-group">
            {% if form.permissions.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.permissions.errors}}</div>
            {% endif %}
            <label for="id_permissions" class="col-sm-2 control-label">Permissions:</label>
            <div class="col-sm-10">
                {{form.permissions}}
            </div>
        </div>

        <input type="hidden" name="company" value="{{company}}" />

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-default">Submit Request</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

app/templates/new_contractor_request.html
{% extends "basenav.html" %}

{% block title %}New Contractor Request | AMP{% endblock %}

{% block content %}

<!-- Jumbotron -->
<div class="jumbotron">
    <div class="container">
        <h1>New Contractor Request!</h1>
        <p>After supplying the required information and succesfuly sending this form, your request will be given to the proper employee at the company you have requested.</p>
    </div>
</div>

<div class="container">
    <form class="form-horizontal" role="form" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">{{form.non_field_errors}}</div>
        {% endif %}

        <div class="form-group">
            {% if form.company.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.company.errors}}</div>
            {% endif %}
            <label for="id_company" class="col-sm-2 control-label">Company:</label>
            <div class="col-sm-10">
                {{form.company}}
            </div>
        </div>

        <div class="form-group">
            {% if form.first_name.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.first_name.errors}}</div>
            {% endif %}
            <label for="id_first_name" class="col-sm-2 control-label">First Name:</label>
            <div class="col-sm-10">
                {{form.first_name}}
            </div>
        </div>

        <div class="form-group">
            {% if form.last_name.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.last_name.errors}}</div>
            {% endif %}
            <label for="id_last_name" class="col-sm-2 control-label">Last Name:</label>
            <div class="col-sm-10">
                {{form.last_name}}
            </div>
        </div>


        <div class="form-group">
            {% if form.email.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.email.errors}}</div>
            {% endif %}
            <label for="id_email" class="col-sm-2 control-label">Email:</label>
            <div class="col-sm-10">
                {{form.email}}
            </div>
        </div>

        <div class="form-group">
            {% if form.employer.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.employer.errors}}</div>
            {% endif %}
            <label for="id_employer" class="col-sm-2 control-label">Employer:</label>
            <div class="col-sm-10">
                {{form.employer}}
            </div>
        </div>

        <div class="form-group">
            {% if form.permissions.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.permissions.errors}}</div>
            {% endif %}
            <label for="id_permissions" class="col-sm-2 control-label">Permissions:</label>
            <div class="col-sm-10">
                {{form.permissions}}
            </div>
        </div>

        <div class="form-group">
            {% if form.remote.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.remote.errors}}</div>
            {% endif %}
            <label for="id_remote" class="col-sm-2 control-label">Remote:</label>
            <div class="col-sm-10">
                {{form.remote}}
            </div>
        </div>

        <div class="form-group">
            {% if form.background_check.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.background_check.errors}}</div>
            {% endif %}
            <label for="id_background_check" class="col-sm-2 control-label">Background Check:</label>
            <div class="col-sm-10">
                {{form.background_check}}
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-default">Submit Request</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

app/templates/new_employee.html
{% extends "basenav.html" %}

{% block title %}New Employee | AMP{% endblock %}

{% block content %}

<!-- Jumbotron -->
<div class="jumbotron">
    <div class="container">
        <h1>New Employee!</h1>
        <p>This page allows you to create a new Employee.</p>
    </div>
</div>

<div class="container">
    <form class="form-horizontal" role="form" method="post">
        {% csrf_token %}

        {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">{{form.non_field_errors}}</div>
        {% endif %}

        <div class="form-group">
            {% if form.eid.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.eid.errors}}</div>
            {% endif %}
            <label for="id_eid" class="col-sm-2 control-label">EID:</label>
            <div class="col-sm-10">
                {{form.eid}}
            </div>
        </div>

        <div class="form-group">
            {% if form.first_name.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.first_name.errors}}</div>
            {% endif %}
            <label for="id_first_name" class="col-sm-2 control-label">First Name:</label>
            <div class="col-sm-10">
                {{form.first_name}}
            </div>
        </div>

        <div class="form-group">
            {% if form.last_name.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.last_name.errors}}</div>
            {% endif %}
            <label for="id_last_name" class="col-sm-2 control-label">Last Name:</label>
            <div class="col-sm-10">
                {{form.last_name}}
            </div>
        </div>

        <div class="form-group">
            {% if form.permissions.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.permissions.errors}}</div>
            {% endif %}
            <label for="id_permissions" class="col-sm-2 control-label">Permissions:</label>
            <div class="col-sm-10">
                {{form.permissions}}
            </div>
        </div>

        <input type="hidden" name="company" value="{{company}}" />

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-default">Submit Request</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

app/templates/new_employee_request.html
{% extends "basenav.html" %}

{% block title %}New Employee Request | AMP{% endblock %}

{% block content %}

<!-- Jumbotron -->
<div class="jumbotron">
    <div class="container">
        <h1>New Employee Request!</h1>
        <p>After supplying the required information and succesfuly sending this form, your request will be given to the proper employee at the company you have requested.</p>
    </div>
</div>

<div class="container">
    <form class="form-horizontal" role="form" method="post">
        {% csrf_token %}

        {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">{{form.non_field_errors}}</div>
        {% endif %}

        <div class="form-group">
            {% if form.company.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.company.errors}}</div>
            {% endif %}
            <label for="id_company" class="col-sm-2 control-label">Company:</label>
            <div class="col-sm-10">
                {{form.company}}
            </div>
        </div>


        <div class="form-group">
            {% if form.employee.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.employee.errors}}</div>
            {% endif %}
            <label for="id_employee" class="col-sm-2 control-label">Employee:</label>
            <div class="col-sm-10">
                {{form.employee}}
            </div>
        </div>

        <div class="form-group">
            {% if form.permissions.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.permissions.errors}}</div>
            {% endif %}
            <label for="id_permissions" class="col-sm-2 control-label">Permissions:</label>
            <div class="col-sm-10">
                {{form.permissions}}
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-default">Submit Request</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

app/templates/update_contractor.html
{% extends "basenav.html" %}

{% block title %}Read/Update Contractor | AMP{% endblock %}

{% block content %}

<!-- Jumbotron -->
<div class="jumbotron">
    <div class="container">
        <h1>Read/Update Contractor</h1>
        <p>This page allows you to read and update a Contractor.</p>
    </div>
</div>

<div class="container">
    <!-- Breadcrumbs -->
    <ol class="breadcrumb">
      <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
      <li><a href="{% url 'contractors' %}">Contractor</a></li>
      <li class="active">{{name}}</li>
    </ol>

    <!-- Contractor Update Form -->
    <form class="form-horizontal" role="form" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">{{form.non_field_errors}}</div>
        {% endif %}

        <div class="form-group">
            {% if form.first_name.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.first_name.errors}}</div>
            {% endif %}
            <label for="id_first_name" class="col-sm-2 control-label">First Name:</label>
            <div class="col-sm-10">
                {{form.first_name}}
            </div>
        </div>

        <div class="form-group">
            {% if form.last_name.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.last_name.errors}}</div>
            {% endif %}
            <label for="id_last_name" class="col-sm-2 control-label">Last Name:</label>
            <div class="col-sm-10">
                {{form.last_name}}
            </div>
        </div>

        <div class="form-group">
            {% if form.email.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.email.errors}}</div>
            {% endif %}
            <label for="id_email" class="col-sm-2 control-label">Email:</label>
            <div class="col-sm-10">
                {{form.email}}
            </div>
        </div>

        <div class="form-group">
            {% if form.employer.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.employer.errors}}</div>
            {% endif %}
            <label for="id_employer" class="col-sm-2 control-label">Employer:</label>
            <div class="col-sm-10">
                {{form.employer}}
            </div>
        </div>


        <div class="form-group">
            {% if form.permissions.errors %}
            <div class="col-sm-offset-2 col-sm-10 alert alert-danger">{{form.permissions.errors}}</div>
            {% endif %}
            <label for="id_permissions" class="col-sm-2 control-label">Permissions:</label>
            <div class="col-sm-10">
                {{form.permissions}}
            </div>
        </div>

        <input type="hidden" name="company" value="{{company}}" />

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-default">Submit Request</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}